### ISSUE TITLE
Would you accept a gdsfactory netlisting PR?

### ISSUE THREAD

**Issue by daquintero** [dan-fritchman/Netlist#3]
In order to translate also to GDSFactory netlist format:

https://github.com/gdsfactory/gdsfactory/blob/main/gdsfactory/get_netlist.py

I am happy to do it if it would be accepted.

**Comment by dan-fritchman** [comment]
PRs are welcome!  
We work with some other gdsfactory-project folk regularly.  
It'd be good to sort through what you have in mind first though.  
There are a few things I regard as essential to this `Netlist` package: 

1. Its data model. I.e. the pile of dataclasses that are the "netlist AST/ CST". I would recommend any integration with any other Python library work against this. 
2. The parsers. Turn netlist-text into that data model. These have some particularly hard-won lessons embedded in them. (And there are a lot of, let's say, *much* worse ones out there.) 
3. The writers. Turn that data-model into netlist-text. 

When you say "GDSFactory netlist format" - just what do you mean?  
Do you guys defined a custom netlist (text) format?  
Or do you mean the stuff in the dictionaries here: https://github.com/gdsfactory/gdsfactory/blob/7e8d7b4ec26c770751eced84c037a105dfb7e01d/gdsfactory/get_netlist.py#L149

Just more generally - LMK how you'd imagine these things working together. I'm sure there's some beneficial integration to be had. 

Also perhaps worth noting - similar (in-progress) integration with VLSIR:  
https://github.com/Vlsir/Vlsir/issues/50

**Comment by daquintero** [comment]
Hi Dan,

Thanks for making such a great piece of software through VLSIR, and also your detailed response. Apologies for the radio silence, I guess I was thinking what exactly what I was trying to do. 

I realized it is not possible to just convert a gdsfactory netlist to a SPICE representation, as we need to assign the electrical models for our connectivity. In the end, I ended up implementing generator function based composition from the hdl21 with a parser to compose the SPICE netlists, and eventually simulate. You can see how it is done [here](https://piel.readthedocs.io/en/latest/examples/04_spice_cosimulation.html#Extracting-the-SPICE-circuit-and-assigning-model-parameters). Thanks for the previous feedback! 

I love your project and look forward to keep using it!

Cheers,
Dario

**Comment by dan-fritchman** [comment]
Very cool!
